/*
 * voice_colour_motion_demo.ino
 *
 * Arduino Nano 33 BLE / Nano 33 BLE Sense demo firmware for a university
 * IoT/TinyML project. The sketch uses a simple state machine:
 *
 *   WAITING_FOR_VOICE  -> TinyML keyword "start"
 *   WAITING_FOR_COLOUR -> APDS-9960 detects green
 *   TRACKING_MOVEMENT  -> streams IMU readings as JSON over Serial
 *
 * Serial output is JSON-only for system events and movement updates so a
 * separate Python bridge can forward it to a web API.
 *
 * IMPORTANT:
 * - Set VOICE_MODULE_ENABLED to 1 after you paste in your trained
 *   Edge Impulse model header and confirm the helper code below matches
 *   your teammate's working sketch.
 * - This sketch intentionally leaves clear paste markers around the voice
 *   and colour integration points.
 */

#include <Arduino_APDS9960.h>
#include <Arduino_LSM9DS1.h>

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

static const bool DEBUG_SERIAL = false;
static const bool EMIT_SETUP_STATUS = true;
static const bool EMIT_VOICE_DEBUG = true;
static const bool EMIT_COLOUR_DEBUG = true;

static const float VOICE_START_THRESHOLD = 0.75f;
static const float VOICE_RELEASE_THRESHOLD = 0.35f;
static const unsigned long VOICE_TRIGGER_COOLDOWN_MS = 2000;
static const unsigned long VOICE_DEBUG_INTERVAL_MS = 500;

static const int GREEN_MIN_CLEAR = 120;
static const int GREEN_MIN_ABSOLUTE = 80;
static const int GREEN_MIN_MARGIN = 20;
static const float GREEN_DOMINANCE_RATIO = 1.20f;
static const int GREEN_REQUIRED_STREAK = 3;
static const unsigned long COLOUR_DEBUG_INTERVAL_MS = 300;

static const unsigned long MOVEMENT_INTERVAL_MS = 250;
static const float GRAVITY_ALPHA = 0.92f;
static const float DIRECTION_THRESHOLD = 0.35f;

// Set to 1 after you add the exact Edge Impulse-generated header below.
#define VOICE_MODULE_ENABLED 1

enum SystemState {
  WAITING_FOR_VOICE,
  WAITING_FOR_COLOUR,
  TRACKING_MOVEMENT
};

// ---------------------------------------------------------------------------
// Global state
// ---------------------------------------------------------------------------

static SystemState currentState = WAITING_FOR_VOICE;

static bool voiceReady = false;
static bool colourReady = false;
static bool imuReady = false;

static bool voiceTriggerLatched = false;
static unsigned long lastVoiceTriggerMs = 0;
static unsigned long lastVoiceDebugMs = 0;
static int greenStreak = 0;
static unsigned long lastColourDebugMs = 0;
static unsigned long lastMovementSendMs = 0;

static bool gravityInitialised = false;
static float gravityX = 0.0f;
static float gravityY = 0.0f;
static float gravityZ = 0.0f;

// ---------------------------------------------------------------------------
// Required function declarations
// ---------------------------------------------------------------------------

bool voiceDetectedStart();
bool greenDetected();
void sendMovementData();
void printJsonEvent(const char* eventName);

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

static void debugLog(const char* message);
static bool initColourModule();
static bool initImuModule();
static bool readColourSample(int &r, int &g, int &b, int &clearValue);
static void updateGravityBaseline(float ax, float ay, float az);
static const char* stateName(SystemState state);
static void printJsonBool(bool value);
static void printSetupStatus();
static void printColourDebug(int r, int g, int b, int clearValue, bool greenNow);

#if VOICE_MODULE_ENABLED
// ---------------------------------------------------------------------------
// EDGE IMPULSE PASTE REGION START
// Replace this include with the exact header generated by Edge Impulse.
// The helpers below are adapted from your current microphone sketch.
// If your teammate already has a stable version, paste/merge it here.
// ---------------------------------------------------------------------------

#include <PDM.h>
#include <serhiisotskyi-project-1_inferencing.h>

typedef struct {
  signed short *buffers[2];
  unsigned char buf_select;
  unsigned char buf_ready;
  unsigned int buf_count;
  unsigned int n_samples;
} inference_t;

static inference_t inference;
static bool recordReady = false;
static signed short *sampleBuffer = nullptr;
static bool debug_nn = false;

static bool initVoiceModule();
static float pollStartConfidence();
static void pdmDataReadyInferenceCallback();
static bool microphoneInferenceStart(uint32_t n_samples);
static bool microphoneInferenceRecord(void);
static int microphoneAudioSignalGetData(size_t offset, size_t length, float *out_ptr);
static void microphoneInferenceEnd(void);
static void printVoiceDebug(const ei_impulse_result_t &result);

// ---------------------------------------------------------------------------
// EDGE IMPULSE PASTE REGION END
// ---------------------------------------------------------------------------
#else
static bool initVoiceModule() {
  debugLog("Voice module disabled. Set VOICE_MODULE_ENABLED to 1 after pasting your model header.");
  return false;
}
#endif

// ---------------------------------------------------------------------------
// Arduino lifecycle
// ---------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);
  unsigned long serialWaitStart = millis();
  while (!Serial && (millis() - serialWaitStart) < 3000) {
    delay(10);
  }

  voiceReady = initVoiceModule();
  colourReady = initColourModule();
  imuReady = initImuModule();

  if (EMIT_SETUP_STATUS) {
    printSetupStatus();
  }
}

void loop() {
  switch (currentState) {
    case WAITING_FOR_VOICE:
      if (voiceDetectedStart()) {
        printJsonEvent("voice_start");
        currentState = WAITING_FOR_COLOUR;
      }
      break;

    case WAITING_FOR_COLOUR:
      if (greenDetected()) {
        Serial.println("{\"event\":\"colour_authenticated\",\"colour\":\"green\"}");
        currentState = TRACKING_MOVEMENT;
      }
      break;

    case TRACKING_MOVEMENT:
      sendMovementData();
      break;
  }
}

// ---------------------------------------------------------------------------
// State handlers
// ---------------------------------------------------------------------------

bool voiceDetectedStart() {
  if (!voiceReady) {
    return false;
  }

#if VOICE_MODULE_ENABLED
  const float startConfidence = pollStartConfidence();
  const unsigned long now = millis();

  if (startConfidence < VOICE_RELEASE_THRESHOLD) {
    voiceTriggerLatched = false;
    return false;
  }

  if (startConfidence < VOICE_START_THRESHOLD) {
    return false;
  }

  if (voiceTriggerLatched) {
    return false;
  }

  if ((now - lastVoiceTriggerMs) < VOICE_TRIGGER_COOLDOWN_MS) {
    return false;
  }

  voiceTriggerLatched = true;
  lastVoiceTriggerMs = now;
  return true;
#else
  return false;
#endif
}

bool greenDetected() {
  if (!colourReady) {
    return false;
  }

  int r = 0;
  int g = 0;
  int b = 0;
  int clearValue = 0;

  if (!readColourSample(r, g, b, clearValue)) {
    return false;
  }

  // COLOUR TEAMMATE PASTE REGION:
  // Replace this heuristic with your team's tuned/calibrated logic if needed.
  const bool clearEnough = clearValue >= GREEN_MIN_CLEAR;
  const bool greenStrongEnough = g >= GREEN_MIN_ABSOLUTE;
  const bool greenDominatesRed = g > (int)(r * GREEN_DOMINANCE_RATIO) && (g - r) >= GREEN_MIN_MARGIN;
  const bool greenDominatesBlue = g > (int)(b * GREEN_DOMINANCE_RATIO) && (g - b) >= GREEN_MIN_MARGIN;
  const bool greenNow = clearEnough && greenStrongEnough && greenDominatesRed && greenDominatesBlue;

  if (EMIT_COLOUR_DEBUG && (millis() - lastColourDebugMs) >= COLOUR_DEBUG_INTERVAL_MS) {
    printColourDebug(r, g, b, clearValue, greenNow);
    lastColourDebugMs = millis();
  }

  if (greenNow) {
    greenStreak++;
  } else {
    greenStreak = 0;
  }

  return greenStreak >= GREEN_REQUIRED_STREAK;
}

void sendMovementData() {
  if (!imuReady) {
    return;
  }

  const unsigned long now = millis();
  if ((now - lastMovementSendMs) < MOVEMENT_INTERVAL_MS) {
    return;
  }

  if (!IMU.accelerationAvailable() || !IMU.gyroscopeAvailable()) {
    return;
  }

  float ax = 0.0f;
  float ay = 0.0f;
  float az = 0.0f;
  float gx = 0.0f;
  float gy = 0.0f;
  float gz = 0.0f;

  IMU.readAcceleration(ax, ay, az);
  IMU.readGyroscope(gx, gy, gz);

  updateGravityBaseline(ax, ay, az);
  const float linearVertical = ay - gravityY;

  Serial.print("{\"event\":\"movement\",\"ax\":");
  Serial.print(ax, 3);
  Serial.print(",\"ay\":");
  Serial.print(ay, 3);
  Serial.print(",\"az\":");
  Serial.print(az, 3);
  Serial.print(",\"gx\":");
  Serial.print(gx, 3);
  Serial.print(",\"gy\":");
  Serial.print(gy, 3);
  Serial.print(",\"gz\":");
  Serial.print(gz, 3);

  if (linearVertical >= DIRECTION_THRESHOLD) {
    Serial.print(",\"direction\":\"up\"");
  } else if (linearVertical <= -DIRECTION_THRESHOLD) {
    Serial.print(",\"direction\":\"down\"");
  }

  Serial.println("}");
  lastMovementSendMs = now;
}

void printJsonEvent(const char* eventName) {
  Serial.print("{\"event\":\"");
  Serial.print(eventName);
  Serial.println("\"}");
}

// ---------------------------------------------------------------------------
// Hardware helpers
// ---------------------------------------------------------------------------

static void debugLog(const char* message) {
  if (!DEBUG_SERIAL) {
    return;
  }

  Serial.print("# ");
  Serial.println(message);
}

static bool initColourModule() {
  if (!APDS.begin()) {
    debugLog("APDS-9960 init failed.");
    return false;
  }

  return true;
}

static bool initImuModule() {
  if (!IMU.begin()) {
    debugLog("LSM9DS1 init failed.");
    return false;
  }

  return true;
}

static bool readColourSample(int &r, int &g, int &b, int &clearValue) {
  unsigned long startMs = millis();
  while (!APDS.colorAvailable()) {
    if ((millis() - startMs) > 50) {
      return false;
    }
    delay(2);
  }

  APDS.readColor(r, g, b, clearValue);
  return true;
}

static void updateGravityBaseline(float ax, float ay, float az) {
  if (!gravityInitialised) {
    gravityX = ax;
    gravityY = ay;
    gravityZ = az;
    gravityInitialised = true;
    return;
  }

  gravityX = (GRAVITY_ALPHA * gravityX) + ((1.0f - GRAVITY_ALPHA) * ax);
  gravityY = (GRAVITY_ALPHA * gravityY) + ((1.0f - GRAVITY_ALPHA) * ay);
  gravityZ = (GRAVITY_ALPHA * gravityZ) + ((1.0f - GRAVITY_ALPHA) * az);
}

static const char* stateName(SystemState state) {
  switch (state) {
    case WAITING_FOR_VOICE:
      return "WAITING_FOR_VOICE";
    case WAITING_FOR_COLOUR:
      return "WAITING_FOR_COLOUR";
    case TRACKING_MOVEMENT:
      return "TRACKING_MOVEMENT";
    default:
      return "UNKNOWN";
  }
}

static void printJsonBool(bool value) {
  Serial.print(value ? "true" : "false");
}

static void printSetupStatus() {
  Serial.print("{\"event\":\"setup_status\",\"state\":\"");
  Serial.print(stateName(currentState));
  Serial.print("\",\"voiceReady\":");
  printJsonBool(voiceReady);
  Serial.print(",\"colourReady\":");
  printJsonBool(colourReady);
  Serial.print(",\"imuReady\":");
  printJsonBool(imuReady);
  Serial.println("}");
}

static void printColourDebug(int r, int g, int b, int clearValue, bool greenNow) {
  Serial.print("{\"event\":\"colour_debug\",\"state\":\"");
  Serial.print(stateName(currentState));
  Serial.print("\",\"r\":");
  Serial.print(r);
  Serial.print(",\"g\":");
  Serial.print(g);
  Serial.print(",\"b\":");
  Serial.print(b);
  Serial.print(",\"clear\":");
  Serial.print(clearValue);
  Serial.print(",\"greenNow\":");
  printJsonBool(greenNow);
  Serial.print(",\"streak\":");
  Serial.print(greenStreak);
  Serial.print(",\"thresholds\":{\"clear\":");
  Serial.print(GREEN_MIN_CLEAR);
  Serial.print(",\"green\":");
  Serial.print(GREEN_MIN_ABSOLUTE);
  Serial.print(",\"ratio\":");
  Serial.print(GREEN_DOMINANCE_RATIO, 2);
  Serial.println("}}");
}

#if VOICE_MODULE_ENABLED
// ---------------------------------------------------------------------------
// EDGE IMPULSE PASTE REGION START
// This block mirrors the structure of your current Edge Impulse sketch.
// Keep or replace it with your teammate's known-good version as needed.
// ---------------------------------------------------------------------------

static bool initVoiceModule() {
  run_classifier_init();
  if (!microphoneInferenceStart(EI_CLASSIFIER_SLICE_SIZE)) {
    debugLog("Voice buffer allocation failed.");
    return false;
  }

  return true;
}

static float pollStartConfidence() {
  if (!microphoneInferenceRecord()) {
    if (EMIT_VOICE_DEBUG && (millis() - lastVoiceDebugMs) >= VOICE_DEBUG_INTERVAL_MS) {
      Serial.print("{\"event\":\"voice_debug\",\"state\":\"");
      Serial.print(stateName(currentState));
      Serial.println("\",\"status\":\"buffer_overrun\"}");
      lastVoiceDebugMs = millis();
    }
    return 0.0f;
  }

  signal_t signal;
  signal.total_length = EI_CLASSIFIER_SLICE_SIZE;
  signal.get_data = &microphoneAudioSignalGetData;

  ei_impulse_result_t result = {0};
  EI_IMPULSE_ERROR status = run_classifier_continuous(&signal, &result, debug_nn);
  if (status != EI_IMPULSE_OK) {
    if (EMIT_VOICE_DEBUG && (millis() - lastVoiceDebugMs) >= VOICE_DEBUG_INTERVAL_MS) {
      Serial.print("{\"event\":\"voice_debug\",\"state\":\"");
      Serial.print(stateName(currentState));
      Serial.print("\",\"status\":\"classifier_error\",\"code\":");
      Serial.print((int)status);
      Serial.println("}");
      lastVoiceDebugMs = millis();
    }
    return 0.0f;
  }

  if (EMIT_VOICE_DEBUG && (millis() - lastVoiceDebugMs) >= VOICE_DEBUG_INTERVAL_MS) {
    printVoiceDebug(result);
    lastVoiceDebugMs = millis();
  }

  for (size_t index = 0; index < EI_CLASSIFIER_LABEL_COUNT; index++) {
    if (strcmp(result.classification[index].label, "start") == 0) {
      return result.classification[index].value;
    }
  }

  return 0.0f;
}

static void pdmDataReadyInferenceCallback() {
  int bytesAvailable = PDM.available();
  int bytesRead = PDM.read((char *)&sampleBuffer[0], bytesAvailable);

  if (recordReady) {
    for (int i = 0; i < (bytesRead >> 1); i++) {
      inference.buffers[inference.buf_select][inference.buf_count++] = sampleBuffer[i];

      if (inference.buf_count >= inference.n_samples) {
        inference.buf_select ^= 1;
        inference.buf_count = 0;
        inference.buf_ready = 1;
      }
    }
  }
}

static bool microphoneInferenceStart(uint32_t n_samples) {
  inference.buffers[0] = (signed short *)malloc(n_samples * sizeof(signed short));
  if (inference.buffers[0] == nullptr) {
    return false;
  }

  inference.buffers[1] = (signed short *)malloc(n_samples * sizeof(signed short));
  if (inference.buffers[1] == nullptr) {
    free(inference.buffers[0]);
    return false;
  }

  sampleBuffer = (signed short *)malloc((n_samples >> 1) * sizeof(signed short));
  if (sampleBuffer == nullptr) {
    free(inference.buffers[0]);
    free(inference.buffers[1]);
    return false;
  }

  inference.buf_select = 0;
  inference.buf_count = 0;
  inference.n_samples = n_samples;
  inference.buf_ready = 0;

  PDM.onReceive(&pdmDataReadyInferenceCallback);
  PDM.setBufferSize((n_samples >> 1) * sizeof(int16_t));

  if (!PDM.begin(1, EI_CLASSIFIER_FREQUENCY)) {
    microphoneInferenceEnd();
    return false;
  }

  PDM.setGain(127);
  recordReady = true;
  return true;
}

static bool microphoneInferenceRecord(void) {
  bool ok = true;

  if (inference.buf_ready == 1) {
    ok = false;
  }

  while (inference.buf_ready == 0) {
    delay(1);
  }

  inference.buf_ready = 0;
  return ok;
}

static int microphoneAudioSignalGetData(size_t offset, size_t length, float *out_ptr) {
  numpy::int16_to_float(&inference.buffers[inference.buf_select ^ 1][offset], out_ptr, length);
  return 0;
}

static void microphoneInferenceEnd(void) {
  PDM.end();

  if (inference.buffers[0] != nullptr) {
    free(inference.buffers[0]);
    inference.buffers[0] = nullptr;
  }

  if (inference.buffers[1] != nullptr) {
    free(inference.buffers[1]);
    inference.buffers[1] = nullptr;
  }

  if (sampleBuffer != nullptr) {
    free(sampleBuffer);
    sampleBuffer = nullptr;
  }
}

static void printVoiceDebug(const ei_impulse_result_t &result) {
  Serial.print("{\"event\":\"voice_debug\",\"state\":\"");
  Serial.print(stateName(currentState));
  Serial.print("\",\"threshold\":");
  Serial.print(VOICE_START_THRESHOLD, 3);
  Serial.print(",\"latched\":");
  printJsonBool(voiceTriggerLatched);
  Serial.print(",\"scores\":{");

  for (size_t index = 0; index < EI_CLASSIFIER_LABEL_COUNT; index++) {
    if (index > 0) {
      Serial.print(",");
    }

    Serial.print("\"");
    Serial.print(result.classification[index].label);
    Serial.print("\":");
    Serial.print(result.classification[index].value, 5);
  }

  Serial.println("}}");
}

// ---------------------------------------------------------------------------
// EDGE IMPULSE PASTE REGION END
// ---------------------------------------------------------------------------
#endif
